### ISSUE TITLE
Dragging box Creates new Box and Overlaps 

### ISSUE THREAD

**Issue by MoonRainy21** [CarrotNibbles/llr#3]
Dragging box Creates new Box and Overlaps 

https://github.com/CarrotNibbles/llr/assets/90439847/ba7ea6d1-558d-4ff4-8a0a-f54d2bf0b582

**Comment by coinmoles** [comment]
Were you signed in when this happened?

**Comment by MoonRainy21** [comment]
Yes, this bug doesn't happen when I use mouse though.
When I refresh the Overlapped entries does last.
